---
- name: 'copy bash include file over'
  copy:
    src: gcloud.sh
    dest: /usr/local/etc/bash.d/
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
  - ct-gcloud

- name: 'add public key of Google Cloud repo'
  apt_key:
    state: present
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
  when: gcloud_method == 'apt'
  become: true
  tags:
  - ct-gcloud

- name: 'Google Cloud repo = {{gcloud_state}}'
  apt_repository:
    filename: 'google-cloud.sdk' 
    repo: 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main'
#   repo: deb http://packages.cloud.google.com/apt cloud-sdk-xenial main
    state: '{{gcloud_state}}'
    validate_certs: true
  when: gcloud_method == 'apt'
  register: reg_gcloud_repo
  become: true
  tags:
  - ct-gcloud

- name: 'Google Cloud SDK = {{gcloud_state}}'
  apt:
    name: '{{gcloud_pkg}}'
    update_cache: '{{ reg_gcloud_repo is changed }}'
    state: '{{gcloud_state}}'
  when: gcloud_method == 'apt'
  ignore_errors: '{{ansible_check_mode | bool}}'
  become: true
  tags:
  - ct-gcloud

- name: 'gcloud snap = {{gcloud_state}}'
  snap:
    name: 'google-cloud-sdk'
    classic: true
    state: '{{gcloud_state}}'
  when:
  - ct_distro == 'ubuntu'
  - ct_distro_major | int >= 18
  - gcloud_method == 'snap'
  become: true
  tags:
  - ct-gcloud
...
