---
# --------------------------------

- name: "Copy bash include file over"
  ansible.builtin.copy:
    dest: /usr/local/etc/bash.d/
    group: root
    mode: "0644"
    owner: root
    src: gcloud.sh
  become: true
  tags: ["ct-gcloud"]

- name: "Add public key of Google Cloud repo"
  ansible.builtin.get_url:
    dest: "{{ gcloud_keyring_path }}"
    mode: "0644"
    url: "{{ gcloud_keyring_url }}"
  when: gcloud_method == "apt"
  become: true
  tags: ["ct-gcloud"]

- name: "GCP repo"
  ansible.builtin.apt_repository:
    filename: "google-cloud.sdk"
    repo: "deb [signed-by={{ gcloud_keyring_path }}] {{ gcloud_repo_url }} cloud-sdk main"
    state: "{{ gcloud_state }}"
    validate_certs: true
  when: gcloud_method == "apt"
  register: reg_gcloud_repo
  become: true
  tags: ["ct-gcloud"]

- name: "Install packages"
  ansible.builtin.apt:
    name: "{{ gcloud_pkgs }}"
    update_cache: "{{ reg_gcloud_repo is changed }}"
    state: "{{ gcloud_state }}"
  when: gcloud_method == "apt"
  ignore_errors: "{{ ansible_check_mode | bool }}"
  become: true
  tags: ["ct-gcloud"]

- name: "Manage GCP SDK using snap"
  community.general.snap:
    name: "google-cloud-sdk"
    classic: true
    state: "{{ gcloud_state }}"
  when:
  - ansible_distrobution == "Ubuntu"
  - (ansible_distrobution_major_version.split('.')[0] | int) >= 18
  - gcloud_method == "snap"
  become: true
  tags: ["ct-gcloud"]

# --------------------------------
...
